name: dsu-cs-3005-functionality-check
on: [push]
jobs:

##########################################################################

  pull-code:
    name: Pull source code
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        
##########################################################################

  hello-enabled:
    name: Hello enabled?
    runs-on: self-hosted
    needs: [pull-code]
    continue-on-error: true
    outputs:
      output1: ${{ steps.step1.outcome }}
    env:
      PROGRAM: hello
      ASSIGNMENT: hello
    steps:
      - name: Enabled?
        id: step1
        run: grade_manager --cmd enabled --programs ${{ env.ASSIGNMENT }} --verbose
        
  hello-check:
    name: Build and run hello, if enabled
    runs-on: self-hosted
    needs: [hello-enabled]
    continue-on-error: false
    if: ${{ needs.hello-enabled.outputs.output1 == 'success' }}
    env:
      PROGRAM: hello
      ASSIGNMENT: hello
    steps:
      - run: grade_manager --cmd make --programs ${{ env.PROGRAM }} --verbose
      - run: grade_manager --cmd grade-text --programs ${{ env.PROGRAM }} --acceptance-tests-location ${{ env.ASSIGNMENT }}/acceptance_tests --verbose
        
##########################################################################

  questions-3-enabled:
    name: Questions 3 enabled?
    runs-on: self-hosted
    needs: [pull-code]
    continue-on-error: true
    outputs:
      output1: ${{ steps.step1.outcome }}
    env:
      PROGRAM: questions_3
      ASSIGNMENT: questions_3
    steps:
      - name: Enabled?
        id: step1
        run: grade_manager --cmd enabled --programs ${{ env.ASSIGNMENT }} --verbose
        
  questions-3-check:
    name: Build and test questions_3, if enabled
    runs-on: self-hosted
    needs: [questions-3-enabled]
    continue-on-error: false
    if: ${{ needs.questions-3-enabled.outputs.output1 == 'success' }}
    env:
      PROGRAM: questions_3
      ASSIGNMENT: questions_3
      ASSIGNMENT_NUMBER: 1
    steps:
      - run: grade_manager --cmd make --programs ${{ env.PROGRAM }} --verbose
      - run: grade_manager --cmd grade-text --programs ${{ env.PROGRAM }} --acceptance-tests-location ${{ env.ASSIGNMENT }}/acceptance_tests --verbose
        
  questions-3-unit-tests-enabled:
    name: Questions 3 unit tests enabled?
    runs-on: self-hosted
    needs: [questions-3-enabled]
    continue-on-error: true
    if: ${{ needs.questions-3-enabled.outputs.output1 == 'success' }}
    outputs:
      output1: ${{ steps.step1.outcome }}
    env:
      ASSIGNMENT: questions_3_unit_tests
    steps:
      - name: Enabled?
        id: step1
        run: grade_manager --cmd enabled --programs ${{ env.ASSIGNMENT }} --verbose
        
  questions-3-unit-tests:
    name: Questions 3 Unit Tests
    runs-on: self-hosted
    needs: [questions-3-unit-tests-enabled]
    continue-on-error: false
    if: ${{ needs.questions-3-unit-tests-enabled.outputs.output1 == 'success' }}
    env:
      ASSIGNMENT_NUMBER: 1
    steps:
      - run: grade_manager --cmd unit-test --unit-test-working-directory ${{ github.repository }} --unit-test-assignment-number ${{ env.ASSIGNMENT_NUMBER }} --verbose
        
##########################################################################

  ascii-image-enabled:
    name: ASCII Image enabled?
    runs-on: self-hosted
    needs: [pull-code]
    continue-on-error: true
    outputs:
      output1: ${{ steps.step1.outcome }}
    env:
      PROGRAM: ascii_image
      ASSIGNMENT: ascii_image
    steps:
      - name: Enabled?
        id: step1
        run: grade_manager --cmd enabled --programs ${{ env.ASSIGNMENT }} --verbose
        
  ascii-image-check:
    name: Build and run ascii_image, if enabled
    runs-on: self-hosted
    needs: [ascii-image-enabled]
    continue-on-error: false
    if: ${{ needs.ascii-image-enabled.outputs.output1 == 'success' }}
    env:
      PROGRAM: ascii_image
      ASSIGNMENT: ascii_image
      ASSIGNMENT_NUMBER: 2
    steps:
      - run: grade_manager --cmd make --programs ${{ env.PROGRAM }} --verbose
      - run: grade_manager --cmd grade-text --programs ${{ env.PROGRAM }} --acceptance-tests-location ${{ env.ASSIGNMENT }}/acceptance_tests --verbose

  ascii-image-unit-tests-enabled:
    name: ASCII Image unit tests enabled?
    runs-on: self-hosted
    needs: [ascii-image-enabled]
    continue-on-error: true
    outputs:
      output1: ${{ steps.step1.outcome }}
    env:
      ASSIGNMENT: ascii_image_unit_tests
    steps:
      - name: Enabled?
        id: step1
        run: grade_manager --cmd enabled --programs ${{ env.ASSIGNMENT }} --verbose
        
  ascii-image-unit-tests:
    name: ASCII Image Unit Tests
    runs-on: self-hosted
    needs: [ascii-image-unit-tests-enabled]
    continue-on-error: false
    if: ${{ needs.ascii-image-unit-tests-enabled.outputs.output1 == 'success' }}
    env:
      ASSIGNMENT_NUMBER: 2
    steps:
      - run: grade_manager --cmd unit-test --unit-test-working-directory ${{ github.repository }} --unit-test-assignment-number ${{ env.ASSIGNMENT_NUMBER }} --verbose

##########################################################################        
        
  image-file-enabled:
    name: Image File enabled?
    runs-on: self-hosted
    needs: [pull-code]
    continue-on-error: true
    outputs:
      output1: ${{ steps.step1.outcome }}
    env:
      PROGRAM: image_file
      ASSIGNMENT: image_file
    steps:
      - name: Enabled?
        id: step1
        run: grade_manager --cmd enabled --programs ${{ env.ASSIGNMENT }} --verbose
        
  image-file-check:
    name: Build and run image_file, if enabled
    runs-on: self-hosted
    needs: [image-file-enabled]
    continue-on-error: false
    if: ${{ needs.image-file-enabled.outputs.output1 == 'success' }}
    env:
      PROGRAM: image_file
      ASSIGNMENT: image_file
      ASSIGNMENT_NUMBER: 3
    steps:
      - run: grade_manager --cmd make --programs ${{ env.PROGRAM }} --verbose
      - run: grade_manager --cmd grade-ppm --programs ${{ env.PROGRAM }} --acceptance-tests-location ${{ env.ASSIGNMENT }}/acceptance_tests --image-location images --image-link images --verbose
        
  image-file-unit-tests-enabled:
    name: Image File unit tests enabled?
    runs-on: self-hosted
    needs: [image-file-enabled]
    continue-on-error: true
    outputs:
      output1: ${{ steps.step1.outcome }}
    env:
      ASSIGNMENT: image_file_unit_tests
    steps:
      - name: Enabled?
        id: step1
        run: grade_manager --cmd enabled --programs ${{ env.ASSIGNMENT }} --verbose
        
  image-file-unit-tests:
    name: Image File Unit Tests
    runs-on: self-hosted
    needs: [image-file-unit-tests-enabled]
    continue-on-error: false
    if: ${{ needs.image-file-unit-tests-enabled.outputs.output1 == 'success' }}
    env:
      ASSIGNMENT_NUMBER: 3
    steps:
      - run: grade_manager --cmd unit-test --unit-test-working-directory ${{ github.repository }} --unit-test-assignment-number ${{ env.ASSIGNMENT_NUMBER }} --verbose
        
##########################################################################        
        
  action-data-menu-data-enabled:
    name: ActionData/MenuData enabled?
    runs-on: self-hosted
    needs: [pull-code]
    continue-on-error: true
    outputs:
      output1: ${{ steps.step1.outcome }}
    env:
      ASSIGNMENT: action_data_menu_data_unit_tests
    steps:
      - name: Enabled?
        id: step1
        run: grade_manager --cmd enabled --programs ${{ env.ASSIGNMENT }} --verbose
        
  action-data-menu-data-check:
    name: Build and test ActionData, MenuData, PPM::readStream, if enabled
    runs-on: self-hosted
    needs: [action-data-menu-data-enabled]
    continue-on-error: false
    if: ${{ needs.action-data-menu-data-enabled.outputs.output1 == 'success' }}
    env:
      ASSIGNMENT_NUMBER: 4
    steps:
      - run: grade_manager --cmd unit-test --unit-test-working-directory ${{ github.repository }} --unit-test-assignment-number ${{ env.ASSIGNMENT_NUMBER }} --verbose
        
##########################################################################        

  ppm-menu-enabled:
    name: PPM Menu enabled?
    runs-on: self-hosted
    needs: [pull-code]
    continue-on-error: true
    outputs:
      output1: ${{ steps.step1.outcome }}
    env:
      PROGRAM: ppm_menu
      ASSIGNMENT: ppm_menu
    steps:
      - name: Enabled?
        id: step1
        run: grade_manager --cmd enabled --programs ${{ env.ASSIGNMENT }} --verbose
        
  ppm-menu-check:
    name: Build and run ppm_menu, if enabled
    runs-on: self-hosted
    needs: [ppm-menu-enabled]
    continue-on-error: false
    if: ${{ needs.ppm-menu-enabled.outputs.output1 == 'success' }}
    env:
      PROGRAM: ppm_menu
      ASSIGNMENT: ppm_menu
      ASSIGNMENT_NUMBER: 5
    steps:
      - run: grade_manager --cmd make --programs ${{ env.PROGRAM }} --verbose
      - run: grade_manager --cmd unit-test --unit-test-working-directory ${{ github.repository }} --unit-test-assignment-number ${{ env.ASSIGNMENT_NUMBER }} --verbose
      - run: grade_manager --cmd grade-ppm --programs ${{ env.PROGRAM }} --acceptance-tests-location ${{ env.ASSIGNMENT }}/acceptance_tests --image-location images --image-link images --verbose
        
##########################################################################        
        
  ppm-operators-enabled:
    name: PPM Operators enabled?
    runs-on: self-hosted
    needs: [pull-code]
    continue-on-error: true
    outputs:
      output1: ${{ steps.step1.outcome }}
    env:
      PROGRAM: ppm_menu
      ASSIGNMENT: operator
    steps:
      - name: Enabled?
        id: step1
        run: grade_manager --cmd enabled --programs ${{ env.ASSIGNMENT }} --verbose
        
  ppm-operators-check:
    name: Build and run ppm_menu, if enabled
    runs-on: self-hosted
    needs: [ppm-operators-enabled]
    continue-on-error: false
    if: ${{ needs.ppm-operators-enabled.outputs.output1 == 'success' }}
    env:
      PROGRAM: ppm_menu
      ASSIGNMENT: operator
      ASSIGNMENT_NUMBER: 6
    steps:
      - run: grade_manager --cmd make --programs ${{ env.PROGRAM }} --verbose
      - run: grade_manager --cmd unit-test --unit-test-working-directory ${{ github.repository }} --unit-test-assignment-number ${{ env.ASSIGNMENT_NUMBER }} --verbose
      - run: grade_manager --cmd grade-ppm --programs ${{ env.PROGRAM }} --acceptance-tests-location ${{ env.ASSIGNMENT }}/acceptance_tests --image-location images --image-link images --verbose
        
##########################################################################        
        
  image-filters-enabled:
    name: Image Filters enabled?
    runs-on: self-hosted
    needs: [pull-code]
    continue-on-error: true
    outputs:
      output1: ${{ steps.step1.outcome }}
    env:
      PROGRAM: ppm_menu
      ASSIGNMENT: gray-draw
    steps:
      - name: Enabled?
        id: step1
        run: grade_manager --cmd enabled --programs ${{ env.ASSIGNMENT }} --verbose
        
  image-filters-check:
    name: Build and run ppm_menu, if enabled
    runs-on: self-hosted
    needs: [image-filters-enabled]
    continue-on-error: false
    if: ${{ needs.image-filters-enabled.outputs.output1 == 'success' }}
    env:
      PROGRAM: ppm_menu
      ASSIGNMENT: gray-draw
      ASSIGNMENT_NUMBER: 7
    steps:
      - run: grade_manager --cmd make --programs ${{ env.PROGRAM }} --verbose
      - run: grade_manager --cmd unit-test --unit-test-working-directory ${{ github.repository }} --unit-test-assignment-number ${{ env.ASSIGNMENT_NUMBER }} --verbose
      - run: grade_manager --cmd grade-ppm --programs ${{ env.PROGRAM }} --acceptance-tests-location ${{ env.ASSIGNMENT }}/acceptance_tests --image-location images --image-link images --verbose
        
##########################################################################        
